<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $countries = [
            // Pays africains
            [
                'name' => 'Algérie',
                'code' => 'DZA',
                'phone_code' => '+213',
                'flag' => '🇩🇿',
                'sort_order' => 1,
            ],
            [
                'name' => 'Angola',
                'code' => 'AGO',
                'phone_code' => '+244',
                'flag' => '🇦🇴',
                'sort_order' => 2,
            ],
            [
                'name' => 'Bénin',
                'code' => 'BEN',
                'phone_code' => '+229',
                'flag' => '🇧🇯',
                'sort_order' => 3,
            ],
            [
                'name' => 'Botswana',
                'code' => 'BWA',
                'phone_code' => '+267',
                'flag' => '🇧🇼',
                'sort_order' => 4,
            ],
            [
                'name' => 'Burkina Faso',
                'code' => 'BFA',
                'phone_code' => '+226',
                'flag' => '🇧🇫',
                'sort_order' => 5,
            ],
            [
                'name' => 'Burundi',
                'code' => 'BDI',
                'phone_code' => '+257',
                'flag' => '🇧🇮',
                'sort_order' => 6,
            ],
            [
                'name' => 'Cameroun',
                'code' => 'CMR',
                'phone_code' => '+237',
                'flag' => '🇨🇲',
                'sort_order' => 7,
            ],
            [
                'name' => 'Cap-Vert',
                'code' => 'CPV',
                'phone_code' => '+238',
                'flag' => '🇨🇻',
                'sort_order' => 8,
            ],
            [
                'name' => 'République Centrafricaine',
                'code' => 'CAF',
                'phone_code' => '+236',
                'flag' => '🇨🇫',
                'sort_order' => 9,
            ],
            [
                'name' => 'Tchad',
                'code' => 'TCD',
                'phone_code' => '+235',
                'flag' => '🇹🇩',
                'sort_order' => 10,
            ],
            [
                'name' => 'Comores',
                'code' => 'COM',
                'phone_code' => '+269',
                'flag' => '🇰🇲',
                'sort_order' => 11,
            ],
            [
                'name' => 'Congo',
                'code' => 'COG',
                'phone_code' => '+242',
                'flag' => '🇨🇬',
                'sort_order' => 12,
            ],
            [
                'name' => 'République Démocratique du Congo',
                'code' => 'COD',
                'phone_code' => '+243',
                'flag' => '🇨🇩',
                'sort_order' => 13,
            ],
            [
                'name' => 'Djibouti',
                'code' => 'DJI',
                'phone_code' => '+253',
                'flag' => '🇩🇯',
                'sort_order' => 14,
            ],
            [
                'name' => 'Égypte',
                'code' => 'EGY',
                'phone_code' => '+20',
                'flag' => '🇪🇬',
                'sort_order' => 15,
            ],
            [
                'name' => 'Guinée Équatoriale',
                'code' => 'GNQ',
                'phone_code' => '+240',
                'flag' => '🇬🇶',
                'sort_order' => 16,
            ],
            [
                'name' => 'Érythrée',
                'code' => 'ERI',
                'phone_code' => '+291',
                'flag' => '🇪🇷',
                'sort_order' => 17,
            ],
            [
                'name' => 'Eswatini',
                'code' => 'SWZ',
                'phone_code' => '+268',
                'flag' => '🇸🇿',
                'sort_order' => 18,
            ],
            [
                'name' => 'Éthiopie',
                'code' => 'ETH',
                'phone_code' => '+251',
                'flag' => '🇪🇹',
                'sort_order' => 19,
            ],
            [
                'name' => 'Gabon',
                'code' => 'GAB',
                'phone_code' => '+241',
                'flag' => '🇬🇦',
                'sort_order' => 20,
            ],
            [
                'name' => 'Gambie',
                'code' => 'GMB',
                'phone_code' => '+220',
                'flag' => '🇬🇲',
                'sort_order' => 21,
            ],
            [
                'name' => 'Ghana',
                'code' => 'GHA',
                'phone_code' => '+233',
                'flag' => '🇬🇭',
                'sort_order' => 22,
            ],
            [
                'name' => 'Guinée',
                'code' => 'GIN',
                'phone_code' => '+224',
                'flag' => '🇬🇳',
                'sort_order' => 23,
            ],
            [
                'name' => 'Guinée-Bissau',
                'code' => 'GNB',
                'phone_code' => '+245',
                'flag' => '🇬🇼',
                'sort_order' => 24,
            ],
            [
                'name' => 'Kenya',
                'code' => 'KEN',
                'phone_code' => '+254',
                'flag' => '🇰🇪',
                'sort_order' => 25,
            ],
            [
                'name' => 'Lesotho',
                'code' => 'LSO',
                'phone_code' => '+266',
                'flag' => '🇱🇸',
                'sort_order' => 26,
            ],
            [
                'name' => 'Libéria',
                'code' => 'LBR',
                'phone_code' => '+231',
                'flag' => '🇱🇷',
                'sort_order' => 27,
            ],
            [
                'name' => 'Libye',
                'code' => 'LBY',
                'phone_code' => '+218',
                'flag' => '🇱🇾',
                'sort_order' => 28,
            ],
            [
                'name' => 'Madagascar',
                'code' => 'MDG',
                'phone_code' => '+261',
                'flag' => '🇲🇬',
                'sort_order' => 29,
            ],
            [
                'name' => 'Malawi',
                'code' => 'MWI',
                'phone_code' => '+265',
                'flag' => '🇲🇼',
                'sort_order' => 30,
            ],
            [
                'name' => 'Mali',
                'code' => 'MLI',
                'phone_code' => '+223',
                'flag' => '🇲🇱',
                'sort_order' => 31,
            ],
            [
                'name' => 'Maroc',
                'code' => 'MAR',
                'phone_code' => '+212',
                'flag' => '🇲🇦',
                'sort_order' => 32,
            ],
            [
                'name' => 'Maurice',
                'code' => 'MUS',
                'phone_code' => '+230',
                'flag' => '🇲🇺',
                'sort_order' => 33,
            ],
            [
                'name' => 'Mauritanie',
                'code' => 'MRT',
                'phone_code' => '+222',
                'flag' => '🇲🇷',
                'sort_order' => 34,
            ],
            [
                'name' => 'Mozambique',
                'code' => 'MOZ',
                'phone_code' => '+258',
                'flag' => '🇲🇿',
                'sort_order' => 35,
            ],
            [
                'name' => 'Namibie',
                'code' => 'NAM',
                'phone_code' => '+264',
                'flag' => '🇳🇦',
                'sort_order' => 36,
            ],
            [
                'name' => 'Niger',
                'code' => 'NER',
                'phone_code' => '+227',
                'flag' => '🇳🇪',
                'sort_order' => 37,
            ],
            [
                'name' => 'Nigeria',
                'code' => 'NGA',
                'phone_code' => '+234',
                'flag' => '🇳🇬',
                'sort_order' => 38,
            ],
            [
                'name' => 'Rwanda',
                'code' => 'RWA',
                'phone_code' => '+250',
                'flag' => '🇷🇼',
                'sort_order' => 39,
            ],
            [
                'name' => 'São Tomé-et-Príncipe',
                'code' => 'STP',
                'phone_code' => '+239',
                'flag' => '🇸🇹',
                'sort_order' => 40,
            ],
            [
                'name' => 'Sénégal',
                'code' => 'SEN',
                'phone_code' => '+221',
                'flag' => '🇸🇳',
                'sort_order' => 41,
            ],
            [
                'name' => 'Seychelles',
                'code' => 'SYC',
                'phone_code' => '+248',
                'flag' => '🇸🇨',
                'sort_order' => 42,
            ],
            [
                'name' => 'Sierra Leone',
                'code' => 'SLE',
                'phone_code' => '+232',
                'flag' => '🇸🇱',
                'sort_order' => 43,
            ],
            [
                'name' => 'Somalie',
                'code' => 'SOM',
                'phone_code' => '+252',
                'flag' => '🇸🇴',
                'sort_order' => 44,
            ],
            [
                'name' => 'Afrique du Sud',
                'code' => 'ZAF',
                'phone_code' => '+27',
                'flag' => '🇿🇦',
                'sort_order' => 45,
            ],
            [
                'name' => 'Soudan du Sud',
                'code' => 'SSD',
                'phone_code' => '+211',
                'flag' => '🇸🇸',
                'sort_order' => 46,
            ],
            [
                'name' => 'Soudan',
                'code' => 'SDN',
                'phone_code' => '+249',
                'flag' => '🇸🇩',
                'sort_order' => 47,
            ],
            [
                'name' => 'Tanzanie',
                'code' => 'TZA',
                'phone_code' => '+255',
                'flag' => '🇹🇿',
                'sort_order' => 48,
            ],
            [
                'name' => 'Togo',
                'code' => 'TGO',
                'phone_code' => '+228',
                'flag' => '🇹🇬',
                'sort_order' => 49,
            ],
            [
                'name' => 'Tunisie',
                'code' => 'TUN',
                'phone_code' => '+216',
                'flag' => '🇹🇳',
                'sort_order' => 50,
            ],
            [
                'name' => 'Ouganda',
                'code' => 'UGA',
                'phone_code' => '+256',
                'flag' => '🇺🇬',
                'sort_order' => 51,
            ],
            [
                'name' => 'Zambie',
                'code' => 'ZMB',
                'phone_code' => '+260',
                'flag' => '🇿🇲',
                'sort_order' => 52,
            ],
            [
                'name' => 'Zimbabwe',
                'code' => 'ZWE',
                'phone_code' => '+263',
                'flag' => '🇿🇼',
                'sort_order' => 53,
            ],
            // Autres pays importants
            [
                'name' => 'France',
                'code' => 'FRA',
                'phone_code' => '+33',
                'flag' => '🇫🇷',
                'sort_order' => 100,
            ],
            [
                'name' => 'Belgique',
                'code' => 'BEL',
                'phone_code' => '+32',
                'flag' => '🇧🇪',
                'sort_order' => 101,
            ],
            [
                'name' => 'Suisse',
                'code' => 'CHE',
                'phone_code' => '+41',
                'flag' => '🇨🇭',
                'sort_order' => 102,
            ],
            [
                'name' => 'Canada',
                'code' => 'CAN',
                'phone_code' => '+1',
                'flag' => '🇨🇦',
                'sort_order' => 103,
            ],
            [
                'name' => 'États-Unis',
                'code' => 'USA',
                'phone_code' => '+1',
                'flag' => '🇺🇸',
                'sort_order' => 104,
            ],
        ];

        foreach ($countries as $country) {
            Country::create($country);
        }
    }
}
